apply/urls.py
from django.urls import path, include
from .views import *
app_name = 'apply'

urlpatterns = [
    path('main', main, name="main" ),
    path('application', apply, name="application"),
    path('applyconfirm', applyConfirm, name="applyconfirm"),
    path('result/<slug:cat>', resultConfirm, name="result"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings 
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('interview/', include("interview.urls") ),
    path('apply/', include("apply.urls")),
    path('gallery/', include("gallery.urls")),
    path('', include("main.urls") ),

]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name='main'

urlpatterns = [
    path('',views.main_page,name='main_page' ),
]

apply/forms.py
from django import forms
from apply.models import *

class ApplyForm(forms.ModelForm):

    GRADE = (
        ("1학년", "1학년"),
        ("2학년", "2학년"),
        ("3학년", "3학년"),
        ("4학년", "4학년"),
        ("5학년 이상", "5학년 이상"),
        ("졸업생", "졸업생"),
        ("대학원생", "대학원생"),
    )

    SEMESTER = (
        (1, "1학기"),
        (2, "2학기"),
        (3, "3학기"),
        (4, "4학기"),
        (5, "5학기"),
        (6, "6학기"),
    )

    YES_NO = (
        ("예", "예"),
        ("아니오", "아니오"),
    )

    AGREE_NOR = (
        ("동의", "동의"),
        ("비동의", "비동의"),
    )

    KNOW_ROOT = (
        ("sns", "피로그래밍 공식 SNS(예 - 페이스북, 인스타그램)"),
        ("cafe community", "네이버 카페/동아리 관련 커뮤니티(예 - 스펙업, 링커리어, 캠퍼스픽)"),
        ("everytime", "에브리타임"),
        ("friends", "지인의 소개"),
        ("others", "기타"),
    )
    participate_check = forms.ChoiceField(choices=YES_NO, widget=forms.RadioSelect)
    workshop_check = forms.ChoiceField(choices=YES_NO, widget=forms.RadioSelect)
    info_check = forms.ChoiceField(choices=AGREE_NOR, widget=forms.RadioSelect)
    know_check = forms.ChoiceField(choices=KNOW_ROOT, widget=forms.RadioSelect)
    deposit_check = forms.ChoiceField(choices=AGREE_NOR, widget=forms.RadioSelect)
    sub_major_semester = forms.ChoiceField(choices=SEMESTER, required=False, widget=forms.RadioSelect)
    major_grade = forms.ChoiceField(choices=GRADE, widget=forms.RadioSelect)
    sub_major = forms.CharField(required=False)
    class Meta:
        model = Applicant
        fields = ("participate_check", 
        "workshop_check", 
        "info_check", 
        "deposit_check", 
        "name", 
        "school", 
        "major", 
        "major_grade", 
        "sub_major", 
        "sub_major_semester",
        "address",
        "phone_number",
        "avail_meeting_time",
        "answer1",
        "answer2",
        "answer3",
        "answer4",
        "answer5",
        "code",
        "know_check")
        # labels = {
        #     "participate_check":"일정 참여 여부", 
        # "workshop_check":"워크샵 참여 여부", 
        # "info_check" : "개인정보 이용동의", 
        # "deposit_check" : "보증금 납부 동의", 
        # "name" : "이름", 
        # "school" : "학교", 
        # "major" : "전공 학과", 
        # "major_grade" : "학년", 
        # "sub_major" : "부전공", 
        # "sub_major_semester" : "부전공 이수 학기",
        # "address" : "거주지",
        # "phone_number" : "휴대폰 번호",
        # "avail_meeting_time" : "면접 가능 시간대",
        # "answer1":"",
        # "answer2":"",
        # "answer3":"",
        # "answer4":"",
        # "answer5":"",
        # "code":"코드 입력란",
        # "know_check":"피로그래밍 알게 된 경로",
        # }
        # widgets={
        #     # 'participate_check':forms.RadioSelect,
        #     #'workshop_check':forms.RadioSelect,
        #     #'info_check':forms.RadioSelect,
        #     'major_grade':forms.RadioSelect,
        #     'sub_major_semester':forms.RadioSelect,
        #     'know_check':forms.RadioSelect,
        # }

    def clean_sub_major(self):
        sub_major = self.cleaned_data.get('sub_major')
        print(sub_major)
        if sub_major == '':
            print("claen 확인!")
            return ''
        else :
            print("raw 확인!")
            return sub_major
    
    def clean_sub_major_semester(self):
        semester = self.cleaned_data.get('sub_major_semester')
        print(semester)
        if semester == '':
            print("claen 확인!")
            return 0
        else :
            print("raw 확인!")
            return semester

    def clean_phone_number(self):
        pn = self.cleaned_data.get('phone_number')
        tmplist = list(pn)
        print(tmplist)
        for i in tmplist:
            if i<'0' or i>'9':
                tmplist.remove(i)
        print(tmplist)
        pn = ''.join(tmplist)
        return pn


class ApplyConfirm(forms.Form):
    name = forms.CharField(max_length=15, label="이름")
    phone_number = forms.CharField(max_length=15, label="전화번호")

    def clean_phone_number(self):
        pn = self.cleaned_data.get('phone_number')
        tmplist = list(pn)
        print(tmplist)
        for i in tmplist:
            if i<'0' or i>'9':
                tmplist.remove(i)
        print(tmplist)
        pn = ''.join(tmplist)
        return pn

apply/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.http import HttpResponse
from .models import Season, Image, Applicant
from django.core.exceptions import ObjectDoesNotExist
from django.utils import timezone
from .forms import ApplyForm, ApplyConfirm
from django.contrib import messages

def main(request):

    try:
        season = Season.objects.filter(is_public = True).order_by('-created_at').first()
        print(season)
        if season is None:
            msg = "모집 중인 기수가 없습니다"
            messages.error(request, msg)
            return redirect(reverse('main:main_page'))
    except ObjectDoesNotExist:
        msg = "모집 중인 기수가 없습니다"
        messages.error(request, msg)
        return redirect(reverse('main:main_page'))
    
    number = season.season_num
    img = season.poster
    now = timezone.now()
    print(now)
    if now<=season.doc_screening_end and now>=season.doc_screening_start:
        status = "doc"
        notify_date = None
    elif now<season.doc_result_start and now>season.doc_screening_end:
        status = "doc_result_waiting"
        notify_date = season.doc_result_start
    elif now>=season.doc_result_start and now<=season.doc_result_end:
        status = "doc_result"
        notify_date = None
    elif now>season.doc_result_end and now<season.final_result_open:
        status = "final_result_waiting"
        notify_date = season.final_result_open
    elif now>=season.final_result_open and now<=season.final_result_close:
        status = "final"
        notify_date = None
    else:
        msg = "지원 기간이 아닙니다!"
        messages.error(request, msg)
        return redirect(reverse('main:main_page'))

    print(img)
    doc_info = season.doc_screening_info
    ctx = {
        'number' : number,
        'img' : img,
        'status' : status,
        'notify_date' : notify_date,
        'doc_info' : doc_info,
    }
    return render(request, 'apply/apply_main.html', ctx)
    
def apply(request):
    try:
        season = Season.objects.order_by('-created_at').first()
        if season is None:
            msg = "모집 중인 기수가 없습니다"
            messages.error(request, msg)
            return redirect(reverse('main:main_page'))
    except ObjectDoesNotExist:
        msg = "모집 중인 기수가 없습니다"
        messages.error(request, msg)
        return redirect(reverse('apply:main'))
    print("왔다")
    now = timezone.now()
    if now<=season.doc_screening_end and now>=season.doc_screening_start:
        print("여기도")
        status = "doc"
        if request.method == 'POST':
            form = ApplyForm(request.POST)
            if form.is_valid():
                new_applicant = Applicant(**form.cleaned_data) 
                new_applicant.season = season
                new_applicant.save()

                msg = "지원이 완료되었습니다! 지원 상태 확인을 통해서 추가 확인 해주세요!"
                print(msg)
                messages.success(request, msg)
            else:
                msg = "오류가 발생했습니다. 지원서를 다시 작성해주세요"
                messages.error(request, msg)
            
            return redirect(reverse('apply:main'))
        else:
            form = ApplyForm()
            try:
                images = season.images.order_by('created_at')
            except ObjectDoesNotExist:
                images = None

            ctx ={
                'form':form,
                'season':season,
                'images':images,
            }
            return render(request, 'apply/application.html', ctx)
    else:
        msg = "지금은 지원 기간이 아닙니다!"
        messages.error(request, msg)
    
        return redirect(reverse('apply:main'))


def applyConfirm(request):
    try:
        season = Season.objects.order_by('-created_at').first()
        if season is None:
            msg = "모집 중인 기수가 없습니다"
            messages.error(request, msg)
            return redirect(reverse('main:main_page'))
    except ObjectDoesNotExist:
        msg = "모집 중인 기수가 없습니다"
        messages.error(request, msg)
        return redirect(reverse('apply:main'))
    print("왔다")
    now = timezone.now()

    if  now<season.doc_screening_start or now>=season.doc_result_start:
        msg = "지금은 지원 기간이 아닙니다!"
        messages.error(request,msg)
        return redirect(reverse('apply:main'))

    if request.method == 'GET':
        form = ApplyConfirm()
        ctx={
            'form':form,
        }
        return render(request, 'apply/applyconfirm.html', ctx)
    else:
        form = ApplyConfirm(request.POST)
        print(form)
        if form.is_valid():
            name = form.cleaned_data.get('name')
            phone_number = form.cleaned_data.get('phone_number')
            print(name, phone_number)
            try:
                applicant = Applicant.objects.get(season__season_num = season.season_num, name=name, phone_number=phone_number)
                print(applicant)
                apply_date = applicant.created_at.date()
                msg = f'{name}님! {apply_date}에 피로그래밍 서류 전형 지원 이력이 확인되었습니다! 서류 전형 결과 발표를 기다려주세요'
            except ObjectDoesNotExist:
                msg = "서류전형 지원 이력이 없습니다!"

            messages.error(request, msg)
            return redirect(reverse('apply:applyconfirm'))
        else:
            msg = "확인에 오류가 있습니다! 다시 입력해 주세요"
            messages.error(request, msg)
            return redirect(reverse('apply:applyconfirm'))


def resultConfirm(request, cat):
    result_category = str(cat)
    season = Season.objects.order_by('-created_at').first()
    now = timezone.now()
    
    if result_category == 'doc' and (now>=season.doc_result_start and now<=season.doc_result_end):
        if request.method =='GET':
            form = ApplyConfirm()
            ctx = {
                'result_category':result_category,
                'form':form,
            }
            return render(request, 'apply/result_confirm.html', ctx)
        else:
            form = ApplyConfirm(request.POST)
            if form.is_valid():
                name = form.cleaned_data.get('name')
                phone_number = form.cleaned_data.get('phone_number')
                try:
                    applicant = Applicant.objects.get(season__season_num = season.season_num, name=name, phone_number=phone_number)
                except ObjectDoesNotExist:
                    msg = "지원자 명단에 없습니다. 지원 여부를 다시한번 확인해주세요"
                    messages.error(request, msg)
                    return redirect("/")
            else:
                msg = "오류가 생겼습니다 재시도 해주세요"
                messages.error(request, msg)
                return redirect("/")
                
            result = applicant.doc_pass
            meeting_datetime = applicant.meeting_date_time
            meeting_place = applicant.season.meeting_place
            ctx = {
                'result_category':result_category,
                'season_number':season.season_num,
                'name':name,
                'result':result,
                'meeting_datetime':meeting_datetime,
                'meeting_place':meeting_place,
                'meeting_info':season.doc_meeting_info,
            }
            return render(request, 'apply/doc_result_page.html', ctx)

    elif result_category == "final" and (now>=season.final_result_open and now<=season.final_result_close):
        if request.method == 'GET':
            form = ApplyConfirm()
            ctx = {
                'result_category':result_category,
                'form':form,
            }
            return render(request, 'apply/result_confirm.html', ctx)
        else:
            form = ApplyConfirm(request.POST)
            if form.is_valid():
                name = form.cleaned_data.get('name')
                phone_number = form.cleaned_data.get('phone_number')
                try:
                    applicant = Applicant.objects.get(season__season_num = season.season_num, name=name, phone_number=phone_number)
                except ObjectDoesNotExist:
                    msg = "지원자 명단에 없습니다. 지원 여부를 다시한번 확인해주세요"
                    messages.error(request, msg)
                    return redirect("/")
            else:
                msg = "오류가 생겼습니다 재시도 해주세요"
                messages.error(request, msg)
                return redirect("/")
            result = applicant.final_pass
            workshop_date = season.workshop_date
            workshop_place = season.workshop_place
            ctx = {
                'result_category':result_category,
                'season_number':season.season_num,
                'name':name,
                'result':result,
                'final_info':season.final_info,
                'workshop_date':workshop_date,
                'workshop_place':workshop_place,
            }
            return render(request, 'apply/final_result_page.html', ctx)

    else:
        msg = "합격자 발표 기간이 아닙니다!"
        messages.error(request, msg)
        return redirect(reverse('main:main_page'))

apply/templates/apply/application.html
{% extends 'layout.html' %} {% load static %} {% block headtitle %} | Join Us {% endblock headtitle %} {% block custom_style %}
<link rel="stylesheet" href="{% static 'css/application.css' %}" />
{% endblock %} {% block titlename %} 피로그래밍 {{season.season_num}}기 지원서 {% endblock titlename %} {% block contents %}
<div class="form_container">
  <form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}

    <div id="application_container">
      <div id="qna_section">
        <div id="number">1</div>
        <div id="qna">
          <div>피로그래밍 모든 일정에 참여 가능한가요?</div>
          <div id="sub_q">
            면접 ( {% if season.meeting_date1 is not None %} {{season.meeting_date1.month}}/{{season.meeting_date1.day}}, {% endif %} {% if season.meeting_date2 is not None %}
            {{season.meeting_date2.month}}/{{season.meeting_date2.day}}, {% endif %} {% if season.meeting_date3 is not None %} {{season.meeting_date3.month}}/{{season.meeting_date3.day}} {% endif %}
            ), 정규세션 ( {{season.session_start_date.year}}/{{season.session_start_date.month}}/{{season.session_start_date.day}} ~
            {{season.session_end_date.year}}/{{season.session_end_date.month}}/{{season.session_end_date.day}} ) 매주 화, 목, 토 (10:00 ~ 17:00 공휴일 제외)
          </div>
          <div>{{form.participate_check}}</div>
        </div>
      </div>
      <div id="qna_section">
        <div id="number">2</div>
        <div id="qna">
          <div id="q">피로그래밍 워크샵({{season.workshop_date.month}}월 {{season.workshop_date.day}}일 {{season.workshop_date.hour}}시 {{season.workshop_date.minute}}분)에 참여 가능한가요?</div>
          <div>{{form.workshop_check}}</div>
        </div>
      </div>

      <div id="qna_section">
        <div id="number">3</div>
        <div id="qna">
          <div id="q">피로그래밍을 알게 된 경로는 어디인가요?</div>
          <div>{{form.know_check}}</div>
        </div>
      </div>

      <div id="qna_section">
        <div id="number">4</div>
        <div id="qna">
          <div>개인정보 이용동의</div>
          <div id="sub_q">본 피로그래밍 {{season.season_num}}기 지원서에 입력한 개인정보는 피로그래밍 신규 회원 모집 및 선발, 피로그래밍 활동에만 이용되며, 이외의 용도로 활용되지 않습니다.</div>
          <div>{{form.info_check}}</div>
        </div>
      </div>

      <div id="qna_section">
        <div id="number">5</div>
        <div id="qna">
          <div>보증금 납부 동의</div>
          <div id="sub_q">
            동아리 활동에는 보증금 제도가 있습니다. 동아리 시작 시 20만 원의 보증금을 내시게 됩니다. 강의(화, 목, 토) 결석이나 과제 미제출 시, 지각이나 늦은 과제 제출 시 보증금에서 차감됩니다. 방학 중
            모든 활동에 정상적으로 참여하시면 활동비를 제외한 나머지 금액을 돌려드립니다. 동아리의 보증금 제도에 동의하십니까?
          </div>
          <div>{{form.deposit_check}}</div>
        </div>
      </div>

      <div id="sub_title">SECTION1. 개인정보</div>

      <div id="qna_section">
        <div id="number">1</div>
        <div id="qna">
          <div>이름</div>
          <div id="sub_q">ex) 김피로</div>
          <div id="input1">{{form.name}}</div>
        </div>
      </div>

      <div id="qna_section">
        <div id="number">2</div>
        <div id="qna">
          <div>학교</div>
          <div id="sub_q">ex) 피로대학교</div>
          <div id="input1">{{form.school}}</div>
        </div>
      </div>

      <div id="qna_section">
        <div id="number">3</div>
        <div id="qna">
          <div>전공 학과</div>
          <div id="sub_q">ex) 웹개발학과</div>
          <div id="input1">{{form.major}}</div>
        </div>
      </div>

      <div id="qna_section">
        <div id="number">4</div>
        <div id="qna">
          <div id="q">(복수 혹은 이중 전공인 경우) 부전공</div>
          <div id="input1">{{form.sub_major}}</div>
        </div>
      </div>

      <div id="qna_section">
        <div id="number">5</div>
        <div id="qna">
          <div id="q">(컴퓨터 관련 학과를 복수, 이중 전공인 경우) 해당 전공 이수 학기</div>
          <div>{{form.sub_major_semester}}</div>
        </div>
      </div>

      <div id="qna_section">
        <div id="number">6</div>
        <div id="qna">
          <div>학년</div>
          <div id="sub_q">휴학 중인 경우, 수료한 학년을 기준으로 선택해주세요</div>
          <div>{{form.major_grade}}</div>
        </div>
      </div>

      <div id="qna_section">
        <div id="number">7</div>
        <div id="qna">
          <div>거주지</div>
          <div id="sub_q">피로그래밍 활동 기간 동안 거주하시는 곳을 입력해주세요</div>
          <div id="input1">{{form.address}}</div>
        </div>
      </div>

      <div id="qna_section">
        <div id="number">8</div>
        <div id="qna">
          <div>휴대폰 번호</div>
          <div id="sub_q">ex) 010-1234-5678</div>
          <div id="input1">{{form.phone_number}}</div>
        </div>
      </div>

      <div id="qna_section">
        <div id="number">9</div>
        <div id="qna">
          <div>면접 가능 시간대</div>
          <div id="sub_q">아래 중 가능한 면접 일시를 모두 써주세요 ex) 1일 오전 / 2일 오후</div>
          <div id="meeting_times">
            {% if season.meeting_date1 is not None %}
            <div>{{season.meeting_date1.month}}월 {{season.meeting_date1.day}}일 오전</div>
            <div>{{season.meeting_date1.month}}월 {{season.meeting_date1.day}}일 오후</div>
            {% endif %} {% if season.meeting_date2 is not None %}
            <div>{{season.meeting_date2.month}}월 {{season.meeting_date2.day}}일 오전</div>
            <div>{{season.meeting_date2.month}}월 {{season.meeting_date2.day}}일 오후</div>
            {% endif %} {% if season.meeting_date3 is not None %}
            <div>{{season.meeting_date3.month}}월 {{season.meeting_date3.day}}일 오전</div>
            <div>{{season.meeting_date3.month}}월 {{season.meeting_date3.day}}일 오후</div>
            {% endif %}
          </div>
          <div id="input1">{{form.avail_meeting_time}}</div>
        </div>
      </div>

      <div id="sub_title">SECTION2. 지원서</div>

      <div id="qna_section">
        <div id="number">1</div>
        <div id="qna">
          <div id="q">{{season.question1}}</div>
          <div id="text_input">{{form.answer1}}</div>
        </div>
      </div>

      <div id="qna_section">
        <div id="number">2</div>
        <div id="qna">
          <div id="q">{{season.question2}}</div>
          <div id="text_input">{{form.answer2}}</div>
        </div>
      </div>

      <div id="qna_section">
        <div id="number">3</div>
        <div id="qna">
          <div id="q">{{season.question3}}</div>
          <div id="text_input">{{form.answer3}}</div>
        </div>
      </div>

      <div id="qna_section">
        <div id="number">4</div>
        <div id="qna">
          <div id="q">{{season.question4}}</div>
          <div id="text_input">{{form.answer4}}</div>
        </div>
      </div>

      <div id="qna_section">
        <div id="number">5</div>
        <div id="qna">
          <div id="q">{{season.question5}}</div>
          <div id="text_input">{{form.answer5}}</div>
        </div>
      </div>

      <div id="sub_title">SECTION3. 코딩테스트</div>

      <div id="coding_test_section">
        <div id="coding_test_info">{{season.coding_test}}</div>

        {% if images is not None %} {% for img in images %}
        <div>{{img.title}}</div>
        <div><img id="coding_test_img" src="{{img.img.url}}" /></div>
        {% endfor %} {% endif %}
        <div id="code_test_q">코딩 테스트 답변 제출</div>
        <div id="sub_q">문제를 어떻게 풀어야할 지 모르겠다면, 점프 투 파이썬(https://wikidocs.net/book/1)을 참고하세요! (특히 클래스 부분을 잘 읽어보시기 바랍니다.)</div>
        <div id="text_input_code">{{form.code}}</div>
      </div>

      <div id="sub_title">SECTION4. 최종 확인</div>

      <div id="last_check">지원서를 한 번 제출하면 수정이 불가능 합니다! 따라서 신중히 검토 후 제출해주시기 바랍니다!</div>
      <div id="last_check">
        선발 과정에서의 문의 사항은 피로그래밍 이메일 (pirogramming.official@gmail.com)혹은 카카오톡 플러스친구 (@피로그래밍)로 연락주시기 바랍니다. 빠른 시일 안에 답장 드리겠습니다.
      </div>

      <div id="submit_section"><input type="submit" value="제출하기" /></div>
    </div>

    {% if messages %} {% for message in messages %} {% if message.tags %}
    <script>
      alert("{{ message }}");
    </script>
    {% endif %} {% endfor %} {% endif %}
  </form>
</div>

{% endblock contents %}

apply/templates/apply/apply_main.html
{% extends 'layout.html' %} {% load static %}
<!--  -->
{% block headtitle %}| Join Us{% endblock %} {% block custom_style %}
<link rel="stylesheet" href="{% static 'css/apply_main.css' %}" />
{% endblock %} {% block titlename %} Join Us {% endblock %} {% block contents %}
{% if messages %} {% for message in messages %} {% if message.tags %}
<script>
  alert("{{ message }}");
</script>
{% endif %} {% endfor %} {% endif %}

<div>
  <div id="img_section">
    <img id="poster" src="{{img.url}}" />
  </div>
  <div id="btn_section">
    {% if status == 'doc' %}
    
        {% if doc_info != '' %}
        <div id="doc_info">
            {{doc_info}}
        </div>
        {% endif %}
        
    
    <a id="a_section" href="{% url 'apply:application' %}">
      <div id="apply">지원하기</div>
    </a>
    {% endif %} {% if status == 'doc_result_waiting' %}
    <div id="doc_waiting_info1">서류 전형 지원 기간이 마감되었습니다.</div>
    <div id="doc_waiting_info2">
      서류 전형 합격자 발표일시는 {{notify_date.month}}월 {{notify_date.day}}일
      {{notify_date.hour}}시 {{notify_date.minute}}분입니다
    </div>
    {% endif %} {% if status == 'doc' or status == 'doc_result_waiting' %}
    <a id="a_section" href="{% url 'apply:applyconfirm' %}">
      <div id="btn">지원 상태 확인</div>
    </a>
    {% endif %} {% if status == 'doc_result' %}
    <a id="a_section" href="{% url 'apply:result' 'doc' %}"><div id="btn">서류전형 합격 조회</div></a>
    {% endif %} {% if status == 'final_result_waiting' %}
    <div id="final_waiting_info1">피로그래밍에 대한 많은 관심 감사드립니다</div>
    <div id="final_wating_info2">
      최종 합격자 발표일시는 {{notify_date.month}}월 {{notify_date.day}}일
      {{notify_date.hour}}시 {{notify_date.minute}}분입니다
    </div>
    {% endif %} {% if status == 'final' %}
    <a id="a_section" href="{% url 'apply:result' 'final' %}"><div id="btn">최종 합격 조회</div></a>
    {% endif %}
  </div>
</div>

{% endblock contents %}

apply/templates/apply/applyconfirm.html
{% extends 'layout.html' %} {% load static %} {% block headtitle %}| Join Us{% endblock headtitle %} {% block custom_style %}
<link rel="stylesheet" href="{% static 'css/apply_confirm.css' %}" />
{% endblock %} {% block titlename %} 지원 상태 확인 {% endblock titlename %} {% block contents %}

<div class="main_container">
  <div id="form_section">
    <form action="" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      <div id="name_section">
        <div id="name">이름을 입력해주세요</div>
        <div id="name_field">{{ form.name }}</div>
      </div>

      <div id="phone_number_section">
        <div id="phone_number">전화번호를 입력해주세요</div>
        <div id="phone_number_field">{{form.phone_number}}</div>
      </div>
      <input id="submit_btn" type="submit" value="확인" />
      {% if messages %} {% for message in messages %} {% if message.tags %}
      <script>
        alert("{{ message }}");
      </script>
      {% endif %} {% endfor %} {% endif %}
    </form>
  </div>
</div>

{% endblock contents %}

apply/templates/apply/result_confirm.html
{% extends 'layout.html' %} {% load static %} {% block headtitle %} | Join Us{% endblock headtitle %} {% block custom_style %}
<link rel="stylesheet" href="{% static 'css/result_confirm.css' %}" />
{% endblock %} {% block titlename %} {% if result_category == 'doc' %} 1차 합격 결과 조회 {% elif result_category == 'final' %} 최종 합격 결과 조회 {% endif %} {% endblock titlename %}
<!--  -->
{% block contents %}
<div class="main_container">
  <div id="form_section">
    <form action="" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      <div id="name_section">
        <div id="name">이름을 입력해주세요</div>
        <div id="name_field">{{ form.name }}</div>
      </div>

      <div id="phone_number_section">
        <div id="phone_number">전화번호를 입력해주세요</div>
        <div id="phone_number_field">{{form.phone_number}}</div>
      </div>
      <input id="submit_btn" type="submit" value="확인" />
      {% if messages %} {% for message in messages %} {% if message.tags %}
      <script>
        alert("{{ message }}");
      </script>
      {% endif %} {% endfor %} {% endif %}
    </form>
  </div>
</div>
{% endblock contents %}